### ISSUE TITLE
[Elixir] Adding a single-line "fn" breaks endwise

### ISSUE THREAD

**Issue by danieljaouen** [tpope/vim-endwise#100]
For example:
```
defmodule Test do
  def hello do
    fun = fn time -> time end
  end
end
```
Open a new line above the `fn` definition and add a `quote do` block.  Expect:
```
defmodule Test do
  def hello do
    quote do
      |
    end
    fun = fn time -> time end
  end
end
```

Get:
```
defmodule Test do
  def hello do
    quote do
      |
    fun = fn time -> time end
  end
end
```

**Comment by danieljaouen** [comment]
I think the problem is the use of `searchpair` here: https://github.com/tpope/vim-endwise/blob/master/plugin/endwise.vim#L130

`a:beginpat` matches either `do` or `fn`, but the call to `searchpair` doesn't check to see if the "other" pattern matches (which it would when there's a `fn` underneath a `do`block).

**Comment by danieljaouen** [comment]
Actually, scratch that, even a `fn ->` block fails to open an `end`.  Not sure what the problem is.

**Comment by danieljaouen** [comment]
Ah, I see.  `s:mysearchpair` matches on either `do` or `fn` and it picks up the `do` keyword even if you add a `fn ->` block.

**Comment by danieljaouen** [comment]
My (current) solution to this is to check for a pattern match in `s:mysearchpair` (see: https://github.com/danieljaouen/vim-endwise/commit/fa93e76015a69939201a239bd2d00cdd6f7e5ea4)

**Comment by sodapopcan** [comment]
4289889a fixes this.  I neglected to reference this in the commit message.
