### ISSUE TITLE
endwise breaks vim-asyncomplete keybindings

### ISSUE THREAD

**Issue by duganchen** [tpope/vim-endwise#105]
If this is the entirety of my .vimrc:

    scriptencoding utf-8

    if filereadable(expand('$VIMRUNTIME/defaults.vim'))
        unlet! g:skip_defaults_vim
        source $VIMRUNTIME/defaults.vim
    endif

    packadd minpac
    call minpac#init()

    call minpac#add('tpope/vim-endwise')

    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

Then pressing ENTER in INSERT MODE inserts the following:

    pumvisible() ? "\" : "\
    "

This is a problem because the [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim) project recommends this exact keymapping in its README file.

**Comment by tpope** [comment]
Try using the canonical capitalization of `<CR>`, in both places.

**Comment by duganchen** [comment]
It didn't make a difference.

**Comment by duganchen** [comment]
If I just copy and paste that, then this happens when I press ENTER in INSERT mode:

    =pumvisible() ? "\^Y" : "\
    E114: Missing quote: "\

**Comment by tpope** [comment]
You can try moving it into a function. I don't really have time to pursue further.

**Comment by smarquez1** [comment]
Related to this issue. Check out @roxma 's comment for a workaround:

https://github.com/roxma/nvim-completion-manager/issues/49#issuecomment-285923119

**Comment by starwing** [comment]
After some research I used these code to solve this issue:
```VimL
function! SendCY()
    call feedkeys("\<C-Y>", "t")
    return ""
endfunction
function! SendCR()
    call feedkeys("\<C-Y>", "n")
    return ""
endfunction
imap <silent> <CR> <C-R>=(pumvisible() ? SendCY() : SendCR())<CR>

```
