### ISSUE TITLE
Configuration mechanism for customizing rules

### ISSUE THREAD

**Issue by deathlyfrantic** [tpope/vim-endwise#110]
Would you be open/willing to provide a way to customize the rules (i.e. `b:endwise_*` vars)? I'd like to add some behavior for C files but I cannot define the rules myself because Endwise's default FileType autocmd just overwrites whatever I define.

**Comment by deathlyfrantic** [comment]
Actually, I realized what I want to do will require some changes to the code beyond adding rules, so it's probably best if I just maintain my own fork.

**Comment by tpope** [comment]
Autocommand order can be tricky but it definitely should be possible to override the variables. Try an `after/plugin/` file.
