### ISSUE TITLE
[Request] Trigger when (o)pening new line

### ISSUE THREAD

**Issue by Sircular** [tpope/vim-endwise#116]
I often will start a line, go back and edit part of it, and then use `o` to open a new line.  In this case, endwise is not triggered. Would it be possible (and without undesirable side effects) to trigger endwise when a new line is opened?

**Comment by tpope** [comment]
`nmap o A<CR>` might be acceptable.

**Comment by Sircular** [comment]
Well... I hadn't thought of that, but you're right, it seems to work very well. It obviously doesn't need to be added to the plugin; would adding it to the README be acceptable?
