### ISSUE TITLE
Does not autodisable in paste mode in neovim

### ISSUE THREAD

**Issue by rwz** [tpope/vim-endwise#117]
In regular vim (tested on 8.0.1283) when I enable paste mode, endwise does nothing, as expected, but in neovim (tested in 0.3.4 and 0.3.5) paste mode does not disable endwise and pasting code produces a hot mess.

**Comment by tpope** [comment]
It's working as expected for me on 0.3.4. Paste mode is a Vim thing that Endwise doesn't provide explicit support for, so until demonstrated otherwise I'm going to assume this is not an Endwise bug.
