### ISSUE TITLE
[Nvim] Adding automaticly an extra comma for C and Cpp files

### ISSUE THREAD

**Issue by DiantArts** [tpope/vim-endwise#120]
Hi,

I'm trying to bind an extra comma to my <CR> when needed

For that, I've done some imap that works individually, but no together:

1. `autocmd FileType c,cpp imap <expr> ; strpart(getline('.'), col('.')-1, 1) == ";" ? "\<Right>" : ";"`
2. `autocmd FileType c,cpp imap <expr> <CR> virtcol('.') < 2 ? "" : ";<Left>"`
3. `autocmd FileType c,cpp imap <expr> <CR> <CR><C-f>`

(btw <C-f> is my auto indent)

The problem now is that it's really hard to merge the second and the third one. It would be great if something like the following code would work, but it doesn't...
`autocmd FileType c,cpp imap <expr> <CR> <CR><C-f>virtcol('.') < 2 ? "" : ";<Left>"`

Well, for now i'm blocked... Any idea ?

Thanks in advence

PS: sorry for my lack of english/github

**Comment by tpope** [comment]
This doesn't look Endwise related; correct me if I'm wrong.
