### ISSUE TITLE
Update installation docs

### ISSUE THREAD

**Issue by everettvody** [tpope/vim-endwise#122]
I wanted to try this out, but I couldn't figure out how to install it.  This looks like a cool plugin that exactly what I need, but without a blurb in the README about simple installation, I don't know how to take advantage of your hard work.  

How do I get this installed without some VIM plugin manager?  Are there any tweaks that need to be made to my `.vimrc`?

Thanks!

**Comment by tpope** [comment]
It's the same as any other plugin. See [/tpope/vim-fugitive](Fugitive's README) for example. Bonus, send a PR to update Endwise's instructions to look like those.
