### ISSUE TITLE
vim-endwise paired with nvim-cmp causes neovim to freeze

### ISSUE THREAD

**Issue by brandoncc** [tpope/vim-endwise#129]
First, thanks for all of the amazing plugins that you have provided the community for many years.

I'm trying to use vim-endwise with [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) and the "default" `<CR>` mapping for nvim-cmp causes neovim to freeze when I have vim-endwise installed:

```lua
mapping = {
  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
  ['<C-f>'] = cmp.mapping.scroll_docs(4),
  ['<C-Space>'] = cmp.mapping.complete(),
  ['<C-e>'] = cmp.mapping.close(),
  ['<CR>'] = cmp.mapping.confirm({
    behavior = cmp.ConfirmBehavior.Replace,
    select = true,
  })
}
```

There is another [issue](https://github.com/hrsh7th/nvim-cmp/issues/17) that was related to jiangmiao/auto-pairs and seems like it has basically the same issue with this plugin since it is the same type of plugin.

I think the best way to solve this until hrsh7th has a chance to resolve the incompatibility is to disable endwise while running `cmp.ConfirmBehavior.Replace` and then re-enable it. I'm not sure if that would work, do you think that is a possible solution?

Thanks!

**Comment by hrsh7th** [comment]
I think this issue can be closed. It is a nvim-cmp's bug and it has fixed now.
