### ISSUE TITLE
Delay on enter press

### ISSUE THREAD

**Issue by IngoMeyer441** [tpope/vim-endwise#132]
First, thanks for this nice Vim plugin. :+1: 
Since version 1.3 I experience delays on hitting the enter key (`<CR>` in insert mode). I have tested this when only this plugin was enabled in NeoVim commit `79dcd045d3623ff71903e2806be489bd5fe3200d`. You can hit enter multiple times without the cursor moving onwards on screen. Only pressing another key than enter or leaving the insert mode inserts the blank lines. This happens even in empty files. In original Vim (version 8.2 with patches 1-4464) I could not reproduce the same behavior.

**Comment by tpope** [comment]
Let's start by checking `:verbose imap <CR>`. It could be a few different things depending on if you have another plugin that also maps it.

**Comment by IngoMeyer441** [comment]
`:verbose imap <CR>` returns:
```
i  <CR>        & <CR><SNR>14_(endwise-append)
        Last set from ~/.vim/dein/.cache/init.vim/.dein/plugin/endwise.vim line 140
```

For testing, I used this quite minimal `vimrc`:
```vim
set nocompatible

set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'), expand('~/.vimrc'))

    call dein#add('tpope/vim-endwise')

    call dein#end()
    call dein#save_state()
endif
```

**Comment by tpope** [comment]
https://github.com/neovim/neovim/issues/17911

**Comment by IngoMeyer441** [comment]
Wow, that was fast. Thank you very much for reporting this upstream. I wrongly assumed your latest plugin updates were causing this bug. :sweat_smile:
