### ISSUE TITLE
Doesn't work with `#if 0`

### ISSUE THREAD

**Issue by shyun3** [tpope/vim-endwise#135]
Hello, I tested this with C and I noticed that `#endif` doesn't seem to get inserted if I press enter at the end of this line:
```c
#if 0
```
However, it seems to work fine for `#if 1` or `#if anything-else-really`. Does this plugin have any special consideration for the value `0`?

**Comment by tpope** [comment]
>  Does this plugin have any special consideration for the value `0`?

No, but the syntax highlighting does.
