### ISSUE TITLE
Not working in Ruby for latest commit

### ISSUE THREAD

**Issue by yetrun** [tpope/vim-endwise#138]
It works for commit `4289889a2622f9bc7c594a6dd79763781f63dfb5`.
But it doesn't work for latest commit `210bec5b5306023ba7b04a4e5b0824755ea51d5d`.

**Comment by tpope** [comment]
It's probably a bad interaction with another `<CR>` mapping plugin, as how that worked recently changed. Check `:verbose imap <CR>` to get the culprit.
