### ISSUE TITLE
Does not work with Treesitter installed

### ISSUE THREAD

**Issue by deniciocode** [tpope/vim-endwise#144]
After [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) is installed this plugin seems not to function anymore.

**Comment by deniciocode** [comment]
I think that this issue is none and should not be fixed by this plugin. If this issue is not relevant I am open to have this issue closed.

**Comment by tpope** [comment]
Yeah, I would expect this. Endwise uses the built-in syntax highlighting.

**Comment by RRethy** [comment]
I wrote https://github.com/RRethy/nvim-treesitter-endwise some time ago as a tree-sitter compatible endwise alternative.
