### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by ericgj** [tpope/vim-endwise#15]
I'm sure it's something obvious, but as a complete vim noob I cannot get this plugin to work for me.
If I do `:imap` I do see that the endwise mappings are set, and I am editing a rb file.
But nothing is happening. My .vimrc is

```
set nocompatible
set ff=unix
set ts=8
set sw=4
set sts=4
filetype on
filetype indent on
filetype plugin on
autocmd BufEnter * lcd %:p:h
```

Help?  Thanks.

**Comment by krisleech** [comment]
For me disabling `supertab` plugin "fixed" this.

`:verbose imap <CR>` gives me

```
<CR>          <CR><Plug>DiscretionaryEnd
        Last set from ~/Applications/vimfiles/turbo-vim/bundle/vim-endwise/plugin/endwise.vim
```

**Comment by TristanCrawford** [comment]
The aforementioned `:verbose imap <CR>` was very helpful.

If you're using `blink.pairs`, it's default mappings will also override endwise.

Setting `opts.mappings.enabled = false` in your `blink.pairs` config fixes the problem if you don't care about autopairs.
