### ISSUE TITLE
Confirmations of substitution does not work correctly on command-line window

### ISSUE THREAD

**Issue by tobynet** [tpope/vim-endwise#31]
A document in current buffer is as follows.

```
test
test
test
```

## Expected behaviors

In vim

```
q:i
%s/test/Yeah/gc^M
```
( _^M is an enter key._ )

I can see some confirmations like `replace with Yeah (y/n/a/q/l/^E/^Y)? `  about 3 times.

## Actual behaviors

In vim

```
q:i
%s/test/Yeah/gc^M
```

I can **NOT** see some confirmations like `replace with Yeah (y/n/a/q/l/^E/^Y)? ` .

I see as follows as an alternative,

`search hit BOTTOM, continuing at TOP`

... and already replaced strings **without confirmations.**

```
Yeah
Yeah
Yeah
```

**Comment by sukima** [comment]
@tobynet can you verify PR #79 fixed this and close if so?

**Comment by tobynet** [comment]
:+1:
