### ISSUE TITLE
Feature request: Ctrl+J support

### ISSUE THREAD

**Issue by aleandros** [tpope/vim-endwise#70]
Since Ctrl+J is equivalent to the Enter key (I'm not sure how universal is that though), would it be possible to make the plugin work for both <C-j> and <CR>?

It would be awesome, since I've been using Ctrl+J a lot more than enter (it is way more comfortable with CapsLock mapped to Ctrl).

Thanks!

**Comment by jerryskye** [comment]
Ctrl+M works as well 😜
