### ISSUE TITLE
Adds pumvisible() ? "\" : "\\ to every Enter keypress

### ISSUE THREAD

**Issue by DelvarWorld** [tpope/vim-endwise#75]
This is likely a conflict with another plugin, but whenever I go into insert mode in a file recognized by endwise and hit enter, it adds this to the previous line and then beeps:

        pumvisible() ? "\" : "\\

On every enter press:

            "pumvisible() ? "\\" : "\\
            "pumvisible() ? "\\" : "\\
            "pumvisible() ? "\\" : "\\

Any idea how how to track down what's inserting this? I see that command used in 3 other plugins I have but none of them with that syntax

    ~/.vim/bundle (master ✎ ) $ ack pumvisible

        match-tag/ftplugin/html.vim
        22:    if pumvisible() || (&t_Co < 8 && !has("gui_running"))

        ultisnips/autoload/UltiSnips.vim
        44:    if pumvisible()

        ultisnips/doc/UltiSnips.txt
        1295:  inoremap <silent> <F12> <C-R>=(pumvisible()? "\<LT>C-E>":"")<CR><C-R>=UltiSnipsCallUnite()<CR>
        1296:  nnoremap <silent> <F12> a<C-R>=(pumvisible()? "\<LT>C-E>":"")<CR><C-R>=UltiSnipsCallUnite()<CR>

**Comment by tpope** [comment]
Maybe disable endwise.vim and `:verbose imap <CR>`?

**Comment by DelvarWorld** [comment]
Found it thanks to that command. In fact, it was commented by the ultisnips author. It was in my own .vimrc

    " close the selection list, same as other IDEs.  CONFLICT with some plugins
    " like tpope/Endwise
