### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by gfontenot** [tpope/vim-endwise#84]
Following the suggested guideline of asking before trying to add this myself.

I'd love support for Swift. specifically, for `{` and `(`. I think in general, it'd be safest to put the trailing `}` on a newline and the trailing `)` on the same line.

I'm happy to look into this myself if needed.

**Comment by tpope** [comment]
Sure up until Swift there was zero reason to support something esoteric like curly braces and parentheses.

**Comment by gfontenot** [comment]
:+1: thanks for being such a cool person keep it up
