### ISSUE TITLE
Elixir support does not work for functions

### ISSUE THREAD

**Issue by dkarter** [tpope/vim-endwise#89]
If I write:

``` elixir
defmodule SomeModule do
```

and press `return` vim-endwise will add an `end` on the next line.

However if I type:

``` elixir
def somefunc do
```

and press `return` I don't get an `end`.

Maybe @danieljaouen can help? seeing that he added the elixir support.

**Comment by pbogut** [comment]
@dkarter
Which elixir plugin you are using? I had a similar problem with [vim-polyglot](https://github.com/sheerun/vim-polyglot). Endwise is working fine with [vim-elixir](https://github.com/elixir-lang/vim-elixir). If you using polyglot as well you can disable it for elixir with `let g:polyglot_disabled = ['elixir']`.

**Comment by dkarter** [comment]
Closing since this is now working. Perhaps it was [this commit](https://github.com/tpope/vim-endwise/commit/e66fb6c0606692fee52c6ee3db8f21a46805e4b5) that fixed it.
