### ISSUE TITLE
Broken in new Vim versions after `:hi clear`

### ISSUE THREAD

**Issue by keidax** [tpope/vim-endwise#92]
Since Vim v8.0.0201, endwise has not been working properly (at least in Ruby, I haven't tested other languages). I tracked the issue down to a `:highlight clear` command issued by my colorscheme, and the new behavior of the `synIDattr()` function. I'm not sure if this new behavior is strictly correct from Vim's perspective, or a bug.

**Comment by cweilemann** [comment]
I've had to disable my colorscheme to get it to work with 8.0.329 (127). I should note that it worked for completing method definitions in Ruby, but it wouldn't work for `do` blocks in routes.rb or inside Ruby methods.

**Comment by tpope** [comment]
I can confirm I've noticed some misbehavior too, though haven't had time to
dig in.

**Comment by keidax** [comment]
Tentatively closing thanks to @bmalkus and #93
